### ISSUE TITLE
Erro na chamada accountExists

### ISSUE THREAD

**Issue by kaoecoito** [wirecardBrasil/moip-sdk-java-le#121]
Nas chamadas da API accountExists ocorre o erro abaixo. O motivo é que quando o CPF não é encontrado além do 404 retornar no status do HTTP ele retorno no body da resposta o número 404.
O doRequest analisa se o body tem conteúdo ou se é vazio como critério para tentar fazer o parse do provável JSON de resposta.
O fato de ocorrer o erro no parser não gera problemas no retorno da API, pois ela não repassa a Exception só faz log, mais deixa os logs do servidor com mais debug que o necessário.

com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was NUMBER at line 1 column 4 path $
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:224)
	at com.google.gson.Gson.fromJson(Gson.java:888)
	at com.google.gson.Gson.fromJson(Gson.java:853)
	at com.google.gson.Gson.fromJson(Gson.java:802)
	at com.google.gson.Gson.fromJson(Gson.java:774)
	at br.com.moip.Client.doRequest(Client.java:163)
	at br.com.moip.Client.get(Client.java:89)
	at br.com.moip.api.AccountAPI.checkAccountExists(AccountAPI.java:30)

**Comment by mbnakaya** [comment]
Olá, @kaoecoito!

Investigamos a chamada e encontramos o possível problema. Estamos iniciando o processo de correção.
